name: Build and Run

on:
  push:
  pull_request:

jobs:
  build-run:
    name: Build and run with startup msg verification
    uses: thnkslprpt/cFS/.github/workflows/build-run-app.yml@test
    with:
      startup-string: "TO Lab Initialized"
